//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CK_Customers
    {
        public string CustomerID { get; set; }
        public string Customer { get; set; }
        public string Address { get; set; }
        public string InvoicePrefit { get; set; }
        public Nullable<int> CreditDays { get; set; }
    }
}
