//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_AdminWebSessions
    {
        public string SessionId { get; set; }
        public string ClientId { get; set; }
        public string ClientContact { get; set; }
        public string ClientContactEmail { get; set; }
        public Nullable<System.DateTime> DateLastSessionStart { get; set; }
        public Nullable<System.DateTime> DateLastSessionEnd { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string CreateBy { get; set; }
        public string RecEnabled { get; set; }
        public string ClientContactPhoneN { get; set; }
        public string SessionPwd { get; set; }
        public string AccessLevel { get; set; }
        public string CanViewPrices { get; set; }
        public string CanQuote { get; set; }
        public string CanAproveLotePrecio { get; set; }
    }
}
