//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_SRFColorNew
    {
        public string ID { get; set; }
        public string SrfNo { get; set; }
        public string ColorCode { get; set; }
        public string ColorStandard { get; set; }
        public string ColorWidth { get; set; }
        public Nullable<int> ColorMainQty { get; set; }
        public Nullable<int> ColorCompQty { get; set; }
        public Nullable<int> ColorSubmition { get; set; }
        public string ClientInstructions { get; set; }
        public string ProcessInstructions { get; set; }
        public string Status { get; set; }
        public string Status2 { get; set; }
        public string Condition { get; set; }
        public string ColorRef { get; set; }
        public string DevelopmentNo { get; set; }
        public string ColorDescp { get; set; }
        public string CoralCode { get; set; }
        public Nullable<System.DateTime> DateReq { get; set; }
        public Nullable<System.DateTime> DateAct { get; set; }
        public Nullable<System.DateTime> DateRel { get; set; }
        public Nullable<System.DateTime> DateExp { get; set; }
        public string Season { get; set; }
        public string ExportGuia { get; set; }
        public Nullable<System.DateTime> DateAPR { get; set; }
        public Nullable<System.DateTime> DateReqProg { get; set; }
        public string VoidComments { get; set; }
    }
}
