//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_SrfStyleEspecYarn
    {
        public string LinkCode { get; set; }
        public string SrfNo { get; set; }
        public string YarnType { get; set; }
        public string YarnCount { get; set; }
        public string YarnComposition { get; set; }
        public string YarnCondition { get; set; }
        public string YarnCodeComp { get; set; }
        public string Skuno { get; set; }
        public Nullable<bool> PendingYarn { get; set; }
        public Nullable<int> FabricId { get; set; }
    }
}
