//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_SrfStyleEspec
    {
        public string Id { get; set; }
        public string SrfNo { get; set; }
        public string Component { get; set; }
        public string ComponentType { get; set; }
        public Nullable<int> ShrinkLength { get; set; }
        public Nullable<int> ShrinkWeight { get; set; }
        public Nullable<decimal> FabricWeight { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Skuno { get; set; }
        public string Condition { get; set; }
    }
}
