//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_SRFSpcWidthList
    {
        public EG_SRFSpcWidthList()
        {
            this.EG_SRFSpcFabricWidthDetail = new HashSet<EG_SRFSpcFabricWidthDetail>();
        }
    
        public int Id { get; set; }
        public string SrfNo { get; set; }
        public string Size { get; set; }
        public string ColorWidth { get; set; }
        public string Status { get; set; }
        public string VoidComments { get; set; }
    
        public virtual ICollection<EG_SRFSpcFabricWidthDetail> EG_SRFSpcFabricWidthDetail { get; set; }
        public virtual EG_SRFWebHeader EG_SRFWebHeader { get; set; }
    }
}
