//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EG_SRFSpcColorList
    {
        public int Id { get; set; }
        public string SrfNo { get; set; }
        public string ColorCode { get; set; }
        public string CoralCode { get; set; }
        public string ColorDescp { get; set; }
        public string Status { get; set; }
    }
}
