//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engineer.Net.Infraestructure.BoundedContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EngineerDataBaseEntities : DbContext
    {
        public EngineerDataBaseEntities()
            : base("name=EngineerDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CK_Customers> CK_Customers { get; set; }
        public DbSet<EG_AdminWebSessions> EG_AdminWebSessions { get; set; }
        public DbSet<EG_SRFAttachedFiles> EG_SRFAttachedFiles { get; set; }
        public DbSet<EG_SRFColorNew> EG_SRFColorNew { get; set; }
        public DbSet<EG_SRFColorRequest> EG_SRFColorRequest { get; set; }
        public DbSet<EG_SrfDyeSpecialFinishes> EG_SrfDyeSpecialFinishes { get; set; }
        public DbSet<EG_SrfFabricSpecialFinishes> EG_SrfFabricSpecialFinishes { get; set; }
        public DbSet<EG_SRFSpcColorList> EG_SRFSpcColorList { get; set; }
        public DbSet<EG_SRFSpcFabricList> EG_SRFSpcFabricList { get; set; }
        public DbSet<EG_SRFSpcFabricWidthDetail> EG_SRFSpcFabricWidthDetail { get; set; }
        public DbSet<EG_SRFSpcWidthList> EG_SRFSpcWidthList { get; set; }
        public DbSet<EG_SrfStyleEspec> EG_SrfStyleEspec { get; set; }
        public DbSet<EG_SrfStyleEspecYarn> EG_SrfStyleEspecYarn { get; set; }
        public DbSet<EG_SRFWebHeader> EG_SRFWebHeader { get; set; }
    }
}
